import { BrowserRouter as Router, Routes, Route, Link, useLocation } from 'react-router-dom';
import { useState } from 'react';
import './App.css';
import { Logo } from './components/Logo';
import Home from './pages/Home';
import Features from './pages/Features';
import About from './pages/About';
import Roadmap from './pages/Roadmap';
import Architecture from './pages/Architecture';
import Onboarding from './pages/Onboarding';
import ProfileCreation from './pages/ProfileCreation';
import ProfileSwipe from './pages/ProfileSwipe';

function Navigation() {
  const location = useLocation();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const isActive = (path: string) => location.pathname === path;

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  const closeMobileMenu = () => {
    setIsMobileMenuOpen(false);
  };

  return (
    <>
      <button
        className="mobile-menu-toggle"
        onClick={toggleMobileMenu}
        aria-label="Toggle navigation menu"
        aria-expanded={isMobileMenuOpen}
      >
        <span className="hamburger-line"></span>
        <span className="hamburger-line"></span>
        <span className="hamburger-line"></span>
      </button>
      <nav className={`main-nav ${isMobileMenuOpen ? 'mobile-open' : ''}`} aria-label="Main navigation">
        <Link to="/" className={`nav-link ${isActive('/') ? 'active' : ''}`} aria-current={isActive('/') ? 'page' : undefined} onClick={closeMobileMenu}>Home</Link>
        <Link to="/features" className={`nav-link ${isActive('/features') ? 'active' : ''}`} aria-current={isActive('/features') ? 'page' : undefined} onClick={closeMobileMenu}>Features</Link>
        <Link to="/about" className={`nav-link ${isActive('/about') ? 'active' : ''}`} aria-current={isActive('/about') ? 'page' : undefined} onClick={closeMobileMenu}>About</Link>
        <Link to="/roadmap" className={`nav-link ${isActive('/roadmap') ? 'active' : ''}`} aria-current={isActive('/roadmap') ? 'page' : undefined} onClick={closeMobileMenu}>Roadmap</Link>
        <Link to="/architecture" className={`nav-link ${isActive('/architecture') ? 'active' : ''}`} aria-current={isActive('/architecture') ? 'page' : undefined} onClick={closeMobileMenu}>Architecture</Link>
        <Link to="/onboarding" className={`nav-link ${isActive('/onboarding') ? 'active' : ''}`} aria-current={isActive('/onboarding') ? 'page' : undefined} onClick={closeMobileMenu}>Onboarding</Link>
        <Link to="/profile" className={`nav-link ${isActive('/profile') ? 'active' : ''}`} aria-current={isActive('/profile') ? 'page' : undefined} onClick={closeMobileMenu}>Profile</Link>
        <Link to="/swipe" className={`nav-link ${isActive('/swipe') ? 'active' : ''}`} aria-current={isActive('/swipe') ? 'page' : undefined} onClick={closeMobileMenu}>Swipe</Link>
      </nav>
    </>
  );
}

function App() {
  const location = useLocation();
  const hideHeaderFooter = location.pathname === '/onboarding' || location.pathname === '/profile';

  return (
    <div className="app">
      <a href="#main-content" className="skip-link">Skip to main content</a>
      {!hideHeaderFooter && (
        <header className="app-header">
          <div className="logo-header">
            <Link to="/" className="logo-link" aria-label="Attune home">
              <Logo size={150} className="main-logo" />
            </Link>
            <div className="header-text">
              <h1>Attune</h1>
              <p>A dating app built for how you actually connect.</p>
            </div>
          </div>
          <Navigation />
        </header>
      )}
      <main id="main-content" className={`main-content ${location.pathname.replace('/', '')}`}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/features" element={<Features />} />
          <Route path="/about" element={<About />} />
          <Route path="/roadmap" element={<Roadmap />} />
          <Route path="/architecture" element={<Architecture />} />
          <Route path="/onboarding" element={<Onboarding />} />
          <Route path="/profile" element={<ProfileCreation />} />
          <Route path="/swipe" element={<ProfileSwipe />} />
        </Routes>
      </main>
      {!hideHeaderFooter && (
        <footer className="app-footer">
          <p>© 2026 Attune. This application was generated by Spark103, a product of 103 Software Solutions LLC. All Rights Reserved.</p>
        </footer>
      )}
    </div>
  );
}

function AppWrapper() {
  return (
    <Router basename="/attune-sample-website">
      <App />
    </Router>
  );
}

export default AppWrapper;